import { useEffect, useMemo, useState } from 'react';
import { supabaseProjectStateRepository, type AuthorizationPackageSummary, type ProjectStateStageRequirement } from '../../infrastructure/project-state/supabaseProjectStateRepository';

const resolved=(v:ProjectStateStageRequirement['status'])=>v==='satisfied'||v==='not_applicable';
const label=(v:string)=>v.replaceAll('_',' ');

export function AuthorizationPackageWorkspace({projectStateId,requirements,onRequirementsChanged,onAuthorize,busy}:{projectStateId:string;requirements:ProjectStateStageRequirement[];onRequirementsChanged:(v:ProjectStateStageRequirement[])=>void;onAuthorize:()=>void;busy:boolean}){
 const[summary,setSummary]=useState<AuthorizationPackageSummary|null>(null),[error,setError]=useState<string|null>(null),[loading,setLoading]=useState(true);
 async function reload(){setLoading(true);setError(null);try{const[pkg,req]=await Promise.all([supabaseProjectStateRepository.authorizationPackage(projectStateId),supabaseProjectStateRepository.stageRequirements(projectStateId,'authorization')]);setSummary(pkg);onRequirementsChanged(req)}catch(e){setError(e instanceof Error?e.message:'Authorization package could not load.')}finally{setLoading(false)}}
 useEffect(()=>{void reload()},[projectStateId]);
 const unresolved=useMemo(()=>requirements.filter(r=>r.required&&!resolved(r.status)),[requirements]);
 const ready=Boolean(summary)&&summary!.openDrafts===0&&summary!.unresolvedEvidence===0&&summary!.unresolvedRequired===0&&unresolved.length===0&&summary!.readiness.every(([,v])=>resolved(v));
 if(loading)return <p>Loading authorization package…</p>;
 return <div className="authorization-package">{error?<p className="error-message">{error}</p>:null}<p className="guidance">Project Authorization freezes the exact published preauthorization revisions, readiness, evidence, decisions, conditions and verification basis used for the decision.</p><div className="guided-checklist"><article><strong>Predevelopment domains</strong><span>{summary?.readiness.filter(([,v])=>resolved(v)).length??0}/{summary?.readiness.length??0} ready</span></article><article><strong>Published governed documents</strong><span>{summary?.publishedDocuments??0}</span></article><article><strong>Open document drafts</strong><span>{summary?.openDrafts??0}</span></article><article><strong>Evidence references</strong><span>{summary?.evidence??0}</span></article><article><strong>Unresolved evidence</strong><span>{summary?.unresolvedEvidence??0}</span></article><article><strong>Decisions / approvals</strong><span>{summary?.decisions??0}</span></article></div><h4>Authorization conditions</h4>{requirements.length?<div className="guided-checklist">{requirements.map(r=><article key={r.requirementKey}><strong>{r.label}</strong><span>{label(r.status)}{r.required?' · required':' · optional'}</span>{r.notes?<small>{r.notes}</small>:null}</article>)}</div>:<p>No authorization conditions are currently registered.</p>}{unresolved.length?<p className="guidance">{unresolved.length} required authorization condition{unresolved.length===1?' remains':'s remain'} unresolved.</p>:null}{summary?.openDrafts?<p className="guidance">Publish or discard all open governed drafts before authorization.</p>:null}{summary?.unresolvedEvidence?<p className="guidance">Resolve unknown or unverified evidence before authorization.</p>:null}<div className="form-actions"><button type="button" className="secondary" onClick={()=>void reload()} disabled={busy}>Refresh package</button><button type="button" onClick={onAuthorize} disabled={!ready||busy}>{busy?'Authorizing…':'Authorize project'}</button></div>{!ready?<p className="guidance">Authorization remains unavailable until the governed package is complete.</p>:null}</div>;
}
