import { useCallback, useEffect, useState } from 'react';
import { createProjectStateAction,createProjectStateEvidence,createProjectStateRiskIssue,listProjectStateCrossCutting,recordProjectStateDecision,updateProjectStateAction,updateProjectStateEvidence,updateProjectStateRiskIssue,type CrossCuttingAction,type CrossCuttingEvidence,type CrossCuttingRiskIssue,type KnowledgeState,type ProjectStateCrossCutting,type WorkStatus } from '../../infrastructure/cross-cutting/supabaseCrossCuttingRepository';
import { StageToolLauncher, type StageToolWorkState } from './StageToolLauncher';

type ToolKey='actions'|'risks'|'decisions'|'evidence'|'attention';
const empty:ProjectStateCrossCutting={actions:[],risksIssues:[],decisions:[],evidence:[],attention:{level:'clear',reasons:[],overdueActions:0,blockedActions:0,openMaterialRisks:0,unverifiedEvidence:0}};
const state=(count:number):StageToolWorkState=>count?'in_progress':'not_started';
const statuses:WorkStatus[]=['open','in_progress','blocked','done','cancelled'];
const knowledgeStates:KnowledgeState[]=['known','unknown','unverified','not_applicable'];

export function CrossStageToolsWorkspace({projectStateId}:{projectStateId:string}){
 const[data,setData]=useState<ProjectStateCrossCutting>(empty),[loading,setLoading]=useState(true),[error,setError]=useState<string|null>(null),[feedback,setFeedback]=useState<string|null>(null),[open,setOpen]=useState<ToolKey|null>(null),[busy,setBusy]=useState(false);
 const reload=useCallback(async()=>{setLoading(true);try{setData(await listProjectStateCrossCutting(projectStateId));setError(null)}catch(e){setError(e instanceof Error?e.message:'Cross-stage tools could not load.')}finally{setLoading(false)}},[projectStateId]);
 useEffect(()=>{void reload()},[reload]);
 const run=async(work:()=>Promise<void>,message:string)=>{setBusy(true);setError(null);setFeedback(null);try{await work();await reload();setFeedback(message)}catch(e){setError(e instanceof Error?e.message:'The command could not be completed.')}finally{setBusy(false)}};
 const attentionState:StageToolWorkState=data.attention.level==='blocked'?'blocked':data.attention.level==='attention'?'in_progress':'complete';
 return <section className="panel"><div className="section-heading"><div><p className="eyebrow">Cross-stage controls</p><h3>Project State tools</h3></div>{loading?<small>Loading…</small>:null}</div>{error?<p className="error-message">{error}</p>:null}{feedback?<p className="success-message">{feedback}</p>:null}<div className="stage-tool-grid"><StageToolLauncher label="Actions" description="Open work and accountable next steps" icon="→" state={state(data.actions.length)} onOpen={()=>setOpen(open==='actions'?null:'actions')}/><StageToolLauncher label="Risks / issues" description="Material risks, issues and blockers" icon="!" state={data.risksIssues.some(v=>v.status==='blocked')?'blocked':state(data.risksIssues.length)} onOpen={()=>setOpen(open==='risks'?null:'risks')}/><StageToolLauncher label="Decisions / approvals" description="Governed decisions and authority basis" icon="✓" state={state(data.decisions.length)} onOpen={()=>setOpen(open==='decisions'?null:'decisions')}/><StageToolLauncher label="Evidence / documents" description="Evidence, provenance and knowledge state" icon="▤" state={state(data.evidence.length)} onOpen={()=>setOpen(open==='evidence'?null:'evidence')}/><StageToolLauncher label="Attention" description="Derived blockers, overdue work and evidence gaps" icon="•" state={attentionState} onOpen={()=>setOpen(open==='attention'?null:'attention')}/></div>{open?<div className="stage-tool-surface">{open==='actions'?<Actions projectStateId={projectStateId} rows={data.actions} busy={busy} run={run}/>:null}{open==='risks'?<Risks projectStateId={projectStateId} rows={data.risksIssues} busy={busy} run={run}/>:null}{open==='decisions'?<Decisions projectStateId={projectStateId} rows={data.decisions} busy={busy} run={run}/>:null}{open==='evidence'?<Evidence projectStateId={projectStateId} rows={data.evidence} busy={busy} run={run}/>:null}{open==='attention'?<div><h4>Attention</h4><p className="guidance">{data.attention.level==='clear'?'No current cross-stage attention signals.':data.attention.reasons.join(' · ')}</p><div className="guided-checklist"><article><strong>Blocked actions</strong><span>{data.attention.blockedActions}</span></article><article><strong>Overdue actions</strong><span>{data.attention.overdueActions}</span></article><article><strong>Open material risks</strong><span>{data.attention.openMaterialRisks}</span></article><article><strong>Unknown / unverified evidence</strong><span>{data.attention.unverifiedEvidence}</span></article></div></div>:null}</div>:null}<p className="guidance">These governed controls follow the same Project State across Opportunity, Qualification, Predevelopment and Authorization. Attention is derived from the underlying records and cannot be set manually.</p></section>;
}

type Runner=(work:()=>Promise<void>,message:string)=>Promise<void>;
function Actions({projectStateId,rows,busy,run}:{projectStateId:string;rows:CrossCuttingAction[];busy:boolean;run:Runner}){const[title,setTitle]=useState(''),[due,setDue]=useState('');return <div><h4>Actions</h4><div className="form-grid"><label>New action<input value={title} onChange={e=>setTitle(e.target.value)} placeholder="Required next step"/></label><label>Due date<input type="date" value={due} onChange={e=>setDue(e.target.value)}/></label></div><button disabled={busy||!title.trim()} onClick={()=>void run(async()=>{await createProjectStateAction(projectStateId,title,due);setTitle('');setDue('')},'Action recorded.')}>Add action</button>{rows.length?<div className="guided-checklist">{rows.map(v=><article key={v.id}><strong>{v.title}</strong><span>{v.dueDate?`Due ${v.dueDate} · `:''}{v.status.replaceAll('_',' ')}</span><select aria-label={`Status for ${v.title}`} value={v.status} disabled={busy} onChange={e=>void run(()=>updateProjectStateAction({...v,status:e.target.value as WorkStatus}),'Action updated.')}>{statuses.map(s=><option key={s} value={s}>{s.replaceAll('_',' ')}</option>)}</select></article>)}</div>:<p>No actions recorded.</p>}</div>}
function Risks({projectStateId,rows,busy,run}:{projectStateId:string;rows:CrossCuttingRiskIssue[];busy:boolean;run:Runner}){const[kind,setKind]=useState('risk'),[title,setTitle]=useState(''),[severity,setSeverity]=useState('');return <div><h4>Risks / issues</h4><div className="form-grid"><label>Type<select value={kind} onChange={e=>setKind(e.target.value)}><option value="risk">Risk</option><option value="issue">Issue</option></select></label><label>Title<input value={title} onChange={e=>setTitle(e.target.value)} placeholder="Material risk or issue"/></label><label>Severity<select value={severity} onChange={e=>setSeverity(e.target.value)}><option value="">Not assessed</option><option value="low">Low</option><option value="medium">Medium</option><option value="high">High</option><option value="critical">Critical</option></select></label></div><button disabled={busy||!title.trim()} onClick={()=>void run(async()=>{await createProjectStateRiskIssue(projectStateId,kind,title,severity);setTitle('');setSeverity('')},'Risk / issue recorded.')}>Add risk / issue</button>{rows.length?<div className="guided-checklist">{rows.map(v=><article key={v.id}><strong>{v.title}</strong><span>{v.kind}{v.severity?` · ${v.severity}`:''}</span><select aria-label={`Status for ${v.title}`} value={v.status} disabled={busy} onChange={e=>void run(()=>updateProjectStateRiskIssue({...v,status:e.target.value as WorkStatus}),'Risk / issue updated.')}>{statuses.map(s=><option key={s} value={s}>{s.replaceAll('_',' ')}</option>)}</select></article>)}</div>:<p>No risks or issues recorded.</p>}</div>}
function Decisions({projectStateId,rows,busy,run}:{projectStateId:string;rows:ProjectStateCrossCutting['decisions'];busy:boolean;run:Runner}){const[type,setType]=useState('decision'),[outcome,setOutcome]=useState(''),[rationale,setRationale]=useState(''),[authority,setAuthority]=useState('');return <div><h4>Decisions / approvals</h4><p className="guidance">Recorded decisions are append-only governance history. Corrections require a new decision record rather than overwriting the prior record.</p><div className="form-grid"><label>Type<input value={type} onChange={e=>setType(e.target.value)}/></label><label>Outcome<input value={outcome} onChange={e=>setOutcome(e.target.value)} placeholder="Decision or approval outcome"/></label><label>Rationale<textarea value={rationale} onChange={e=>setRationale(e.target.value)}/></label><label>Authority basis<textarea value={authority} onChange={e=>setAuthority(e.target.value)}/></label></div><button disabled={busy||!type.trim()||!outcome.trim()} onClick={()=>void run(async()=>{await recordProjectStateDecision(projectStateId,type,outcome,rationale,authority);setOutcome('');setRationale('');setAuthority('')},'Decision recorded.')}>Record decision</button>{rows.length?<div className="guided-checklist">{rows.map(v=><article key={v.id}><strong>{v.decisionType.replaceAll('_',' ')}</strong><span>{v.outcome}</span>{v.rationale?<small>{v.rationale}</small>:null}{v.authorityBasis?<small>Authority: {v.authorityBasis}</small>:null}</article>)}</div>:<p>No decisions recorded.</p>}</div>}
function Evidence({projectStateId,rows,busy,run}:{projectStateId:string;rows:CrossCuttingEvidence[];busy:boolean;run:Runner}){const[title,setTitle]=useState(''),[system,setSystem]=useState('google_drive'),[url,setUrl]=useState(''),[note,setNote]=useState(''),[knowledge,setKnowledge]=useState<KnowledgeState>('known');return <div><h4>Evidence / documents</h4><div className="form-grid"><label>Title<input value={title} onChange={e=>setTitle(e.target.value)} placeholder="Evidence or document"/></label><label>Source system<input value={system} onChange={e=>setSystem(e.target.value)}/></label><label>Source reference / URL<input value={url} onChange={e=>setUrl(e.target.value)}/></label><label>Knowledge state<select value={knowledge} onChange={e=>setKnowledge(e.target.value as KnowledgeState)}>{knowledgeStates.map(s=><option key={s} value={s}>{s.replaceAll('_',' ')}</option>)}</select></label><label>Provenance note<textarea value={note} onChange={e=>setNote(e.target.value)}/></label></div><button disabled={busy||!title.trim()} onClick={()=>void run(async()=>{await createProjectStateEvidence(projectStateId,title,system,url,note,knowledge);setTitle('');setUrl('');setNote('');setKnowledge('known')},'Evidence recorded.')}>Add evidence</button>{rows.length?<div className="guided-checklist">{rows.map(v=><article key={v.id}><strong>{v.title}</strong><span>{v.sourceSystem}</span><select aria-label={`Knowledge state for ${v.title}`} value={v.knowledgeState} disabled={busy} onChange={e=>void run(()=>updateProjectStateEvidence({...v,knowledgeState:e.target.value as KnowledgeState}),'Evidence updated.')}>{knowledgeStates.map(s=><option key={s} value={s}>{s.replaceAll('_',' ')}</option>)}</select>{v.provenanceNote?<small>{v.provenanceNote}</small>:null}</article>)}</div>:<p>No evidence recorded.</p>}</div>}
