create or replace function private.assert_cross_stage_project_state_writable(project_state_input uuid)
returns public.project_states
language plpgsql
security definer
set search_path = ''
as $$
declare ps public.project_states;
begin
  select * into ps from public.project_states where id = project_state_input;
  if ps.id is null then raise exception 'Project State not found'; end if;
  if ps.archived_at is not null then raise exception 'Archived Project State is read-only'; end if;
  if not public.is_workspace_member(ps.workspace_id) then raise exception 'Not authorized'; end if;
  if ps.stage not in ('opportunity','qualification','predevelopment','authorization') then raise exception 'Preauthorization cross-stage records are frozen after Project Authorization'; end if;
  return ps;
end;
$$;
revoke all on function private.assert_cross_stage_project_state_writable(uuid) from public, anon, authenticated;

create or replace function public.create_project_state_action_command(project_state_input uuid, title_input text, due_date_input date default null) returns public.actions language plpgsql security invoker set search_path = '' as $$ declare uid uuid := auth.uid(); row_out public.actions; begin if uid is null then raise exception 'Authentication required'; end if; perform private.assert_cross_stage_project_state_writable(project_state_input); if nullif(btrim(title_input),'') is null then raise exception 'Action title is required'; end if; insert into public.actions(project_state_id,title,due_date,status,created_by) values(project_state_input,btrim(title_input),due_date_input,'open',uid) returning * into row_out; return row_out; end; $$;
create or replace function public.update_project_state_action_command(action_input uuid, title_input text, due_date_input date, status_input public.work_status) returns public.actions language plpgsql security invoker set search_path = '' as $$ declare row_out public.actions; begin select * into row_out from public.actions where id=action_input; if row_out.id is null then raise exception 'Action not found'; end if; perform private.assert_cross_stage_project_state_writable(row_out.project_state_id); if nullif(btrim(title_input),'') is null then raise exception 'Action title is required'; end if; update public.actions set title=btrim(title_input),due_date=due_date_input,status=status_input,updated_at=now() where id=action_input returning * into row_out; return row_out; end; $$;
create or replace function public.create_project_state_risk_issue_command(project_state_input uuid, kind_input text, title_input text, severity_input text default null) returns public.risk_issues language plpgsql security invoker set search_path = '' as $$ declare uid uuid := auth.uid(); row_out public.risk_issues; begin if uid is null then raise exception 'Authentication required'; end if; perform private.assert_cross_stage_project_state_writable(project_state_input); if nullif(btrim(kind_input),'') is null or nullif(btrim(title_input),'') is null then raise exception 'Risk/issue kind and title are required'; end if; insert into public.risk_issues(project_state_id,kind,title,severity,status,created_by) values(project_state_input,btrim(kind_input),btrim(title_input),nullif(btrim(severity_input),''),'open',uid) returning * into row_out; return row_out; end; $$;
create or replace function public.update_project_state_risk_issue_command(risk_issue_input uuid, kind_input text, title_input text, severity_input text, status_input public.work_status) returns public.risk_issues language plpgsql security invoker set search_path = '' as $$ declare row_out public.risk_issues; begin select * into row_out from public.risk_issues where id=risk_issue_input; if row_out.id is null then raise exception 'Risk/issue not found'; end if; perform private.assert_cross_stage_project_state_writable(row_out.project_state_id); update public.risk_issues set kind=btrim(kind_input),title=btrim(title_input),severity=nullif(btrim(severity_input),''),status=status_input,updated_at=now() where id=risk_issue_input returning * into row_out; return row_out; end; $$;
create or replace function public.record_project_state_decision_command(project_state_input uuid, decision_type_input text, outcome_input text, rationale_input text default null, authority_basis_input text default null) returns public.decisions language plpgsql security invoker set search_path = '' as $$ declare uid uuid := auth.uid(); row_out public.decisions; begin if uid is null then raise exception 'Authentication required'; end if; perform private.assert_cross_stage_project_state_writable(project_state_input); if nullif(btrim(decision_type_input),'') is null or nullif(btrim(outcome_input),'') is null then raise exception 'Decision type and outcome are required'; end if; insert into public.decisions(project_state_id,decision_type,outcome,rationale,authority_basis,actor_user_id) values(project_state_input,btrim(decision_type_input),btrim(outcome_input),nullif(btrim(rationale_input),''),nullif(btrim(authority_basis_input),''),uid) returning * into row_out; return row_out; end; $$;
create or replace function public.create_project_state_evidence_command(project_state_input uuid, title_input text, source_system_input text default 'google_drive', source_url_input text default null, provenance_note_input text default null, knowledge_state_input public.knowledge_state default 'known') returns public.evidence_references language plpgsql security invoker set search_path = '' as $$ declare uid uuid := auth.uid(); row_out public.evidence_references; begin if uid is null then raise exception 'Authentication required'; end if; perform private.assert_cross_stage_project_state_writable(project_state_input); if nullif(btrim(title_input),'') is null then raise exception 'Evidence title is required'; end if; insert into public.evidence_references(project_state_id,title,source_system,source_url,provenance_note,knowledge_state,created_by) values(project_state_input,btrim(title_input),coalesce(nullif(btrim(source_system_input),''),'google_drive'),nullif(btrim(source_url_input),''),nullif(btrim(provenance_note_input),''),knowledge_state_input,uid) returning * into row_out; return row_out; end; $$;
create or replace function public.update_project_state_evidence_command(evidence_input uuid, title_input text, source_system_input text, source_url_input text, provenance_note_input text, knowledge_state_input public.knowledge_state) returns public.evidence_references language plpgsql security invoker set search_path = '' as $$ declare row_out public.evidence_references; begin select * into row_out from public.evidence_references where id=evidence_input; if row_out.id is null then raise exception 'Evidence not found'; end if; perform private.assert_cross_stage_project_state_writable(row_out.project_state_id); update public.evidence_references set title=btrim(title_input),source_system=coalesce(nullif(btrim(source_system_input),''),'google_drive'),source_url=nullif(btrim(source_url_input),''),provenance_note=nullif(btrim(provenance_note_input),''),knowledge_state=knowledge_state_input where id=evidence_input returning * into row_out; return row_out; end; $$;
revoke execute on function public.create_project_state_action_command(uuid,text,date), public.update_project_state_action_command(uuid,text,date,public.work_status), public.create_project_state_risk_issue_command(uuid,text,text,text), public.update_project_state_risk_issue_command(uuid,text,text,text,public.work_status), public.record_project_state_decision_command(uuid,text,text,text,text), public.create_project_state_evidence_command(uuid,text,text,text,text,public.knowledge_state), public.update_project_state_evidence_command(uuid,text,text,text,text,public.knowledge_state) from public, anon;
grant execute on function public.create_project_state_action_command(uuid,text,date), public.update_project_state_action_command(uuid,text,date,public.work_status), public.create_project_state_risk_issue_command(uuid,text,text,text), public.update_project_state_risk_issue_command(uuid,text,text,text,public.work_status), public.record_project_state_decision_command(uuid,text,text,text,text), public.create_project_state_evidence_command(uuid,text,text,text,text,public.knowledge_state), public.update_project_state_evidence_command(uuid,text,text,text,text,public.knowledge_state) to authenticated;
